SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES
WHERE MANAGER_ID = 114

SELECT EMPLOYEE_ID, SALARY FROM EMPLOYEES
WHERE SALARY > 11999

SELECT JOB_TITLE FROM JOBS
WHERE JOB_ID IN('AC_MGR', 'IT_PROG')

SELECT * FROM DEPARTMENTS
WHERE MANAGER_ID IS NULL

SELECT COUNTRY_ID, COUNTRY_NAME, REGION_ID FROM COUNTRIES
WHERE REGION_ID = 1

SELECT EMPLOYEE_ID, START_DATE, END_DATE FROM JOB_HISTORY
WHERE EMPLOYEE_ID IN('102', '101', '176') OR END_DATE = 'DEC 31, 1998'

SELECT * FROM EMPLOYEES
WHERE JOB_ID IN('AD_PRES')

SELECT COUNT(JOB_ID) FROM EMPLOYEES
WHERE JOB_ID IN('SA_REP', 'ST_CLERK')
GROUP BY JOB_ID
ORDER BY JOB_ID

SELECT JOB_ID, AVG(SALARY) FROM EMPLOYEES
HAVING AVG(SALARY) > 10000
GROUP BY JOB_ID

SELECT SALARY, COUNT(SALARY) "NUMBER_OF_PERSONS" FROM EMPLOYEES
GROUP BY SALARY
ORDER BY SALARY ASC

INSERT INTO jobs (job_id, job_title, min_salary, max_salary)
VALUES ('MK_ASST', 'Marketing Assistant', 3000, 13000)

INSERT INTO employees (employee_id, first_name, last_name, email, phone_number, hire_date, job_id, salary, department_id)
VALUES (500, 'Alicia', 'Santos', 'ASANTOS', '650.124.0000', '03/24/1999', 'MK_ASST', 10000, 20)
