CREATE TABLE SALES_REP
(
    SLSREP_NUMBER                      CHAR(2)         PRIMARY KEY,
    SLSREP_LAST_NAME                   CHAR(10)        NOT NULL,
    SLSREP_FIRST_NAME                  CHAR(10)        NOT NULL,
    SLSREP_GENDER                      CHAR(1)         NOT NULL    CHECK(SLSREP_GENDER IN('F','M','f','m')),
    SLSREP_STREET                      CHAR(15)        NOT NULL,
    SLSREP_CITY                        CHAR(15)        NOT NULL,
    SLSREP_US_STATE                    CHAR(2)         NOT NULL,
    SLSREP_ZIP_CODE                    CHAR(5)         NOT NULL,
    SLSREP_TOTAL_COMMISSION            DECIMAL(7,2)    NOT NULL    CHECK(SLSREP_TOTAL_COMMISSION > 0),
    SLSREP_COMMISSION_RATE             DECIMAL(3,2)    NOT NULL    CHECK(SLSREP_COMMISSION_RATE != 0)
);



CREATE TABLE CUSTOMER
(
    CUSTOMER_NUMBER                      CHAR(3)         PRIMARY KEY,
    CUSTOMER_LAST_NAME                   CHAR(10)        NOT NULL,
    CUSTOMER_FIRST_NAME                  CHAR(8)         NOT NULL,
    CUSTOMER_STREET                      CHAR(15)        NOT NULL,
    CUSTOMER_CITY                        CHAR(15)        NOT NULL,
    CUSTOMER_US_STATE                    CHAR(2)         NOT NULL,
    CUSTOMER_ZIP_CODE                    CHAR(5)         NOT NULL,
    CUSTOMER_BALANCE                     DECIMAL(7,2)    NOT NULL    CHECK(CUSTOMER_BALANCE >= 0),
    CUSTOMER_CREDIT_LIMIT                DECIMAL(6,2)    NOT NULL    CHECK(CUSTOMER_CREDIT_LIMIT != 0),
    CUSTOMER_SLSREP_NUMBER               CHAR(2)         NOT NULL,

    CONSTRAINT CUSTOMER_SLSREP_NUMBER_FK FOREIGN KEY(CUSTOMER_SLSREP_NUMBER) REFERENCES SALES_REP(SLSREP_NUMBER)
);

CREATE TABLE ORDERS
(
    ORDER_NUMBER                CHAR(5)         PRIMARY KEY,
    ORDER_DATE                  DATE            NOT NULL,
    ORDER_CUSTOMER_NUMBER       CHAR(3)         NOT NULL,

    CONSTRAINT ORDER_CUSTOMER_NUMBER_FK FOREIGN KEY(ORDER_CUSTOMER_NUMBER) REFERENCES CUSTOMER(CUSTOMER_NUMBER)
);



CREATE TABLE PART
(
    PART_NUMBER                      CHAR(4)         PRIMARY KEY,
    PART_DESCRIPTION                 CHAR(12)        NOT NULL,
    PART_UNITS_ON_HAND               DECIMAL(4,0)    CHECK(PART_UNITS_ON_HAND >= 0),
    PART_ITEM_CLASS                  CHAR(2)         NOT NULL,
    PART_WAREHOUSE_NUMBER            CHAR(1)         CHECK(PART_WAREHOUSE_NUMBER != 0),
    PART_UNIT_PRICE                  DECIMAL(6,2)    CHECK(PART_UNIT_PRICE <= 0)
);


CREATE TABLE ORDER_LINE
(
    LINE_ORDER_NUMBER                CHAR(3)         PRIMARY KEY,
    LINE_PART_NUMBER                 CHAR(4)         NOT NULL,
    LINE_NUMBER_ORDERED              DECIMAL(3,0)    NOT NULL    CHECK(LINE_NUMBER_ORDERED >= 5),
    LINE_QUOTED_PRICE                DECIMAL(6,2)    NOT NULL    CHECK(LINE_QUOTED_PRICE <= 0),

    CONSTRAINT LINE_ORDER_NUMBER_FK FOREIGN KEY(LINE_ORDER_NUMBER) REFERENCES ORDERS(ORDER_NUMBER),
    CONSTRAINT LINE_PART_NUMBER_FK FOREIGN KEY(LINE_PART_NUMBER) REFERENCES PART(PART_NUMBER)
);
